name: Terraform Checkov and Apply

on:
  push:
    branches:
      - master  # You can specify the branch you want to trigger this workflow on

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Checkov
        run: |
          pip install --user checkov
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run Checkov
        id: checkov
        run: |
          checkov -d ./Compute-Engine
        continue-on-error: true

      - name: Set Checkov output
        id: set-output
        run: echo "checkov_result=$(if [[ -z \$(cat checkov_output.json) ]]; then echo 'success'; else echo 'failure'; fi)" 

  apply:
    needs: checkov
    runs-on: ubuntu-latest
    if: ${{ needs.checkov.outputs.checkov_result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform plan
        run: terraform plan
