name: Terraform Checkov and Apply

on:
  push:
    branches:
      - master  # You can specify the branch you want to trigger this workflow on

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Checkov
        run: |
          pip install --user checkov
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run Checkov
        id: checkov
        run: |
          checkov -d ./Compute-Engine || echo "Checkov found errors"
        continue-on-error: true

  apply:
    needs: checkov
    runs-on: ubuntu-latest
    if: ${{ needs.checkov.outputs.checkov != 'Checkov found errors' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
